### ISSUE TITLE
USER STORY: Manage booking details

### ISSUE THREAD

**Issue by ciarantr** [ciaran-io/himawari-sushi#10]
As a **Site user** **I can** **make changes to my bookings** so that **I can change or cancel my booking**  

### Todo

---
- [x]  Add a bookings link where user can view booking in user dashboard.
  - Show bookings with following booking details.
     - Booking reference
     - Booking confirmed status
     - Booking date
     - Booking time
     - Number of people
     - Special request (massage)
- [x] Add edit booking link that will enable editing the booking
- [x] Add delete booking button that will enable deletion of booking
