### ISSUE TITLE
USER STORY: Newsletter subscription

### ISSUE THREAD

**Issue by ciarantr** [ciaran-io/himawari-sushi#12]
As a **Site User** **I can** **sign up to the newsletter** so that **I can receive offers through email** 

### Todo

---
- [x] Enable sign up users to signup to newsletter
  - [x] Add signup form
  - [x] Add signup confirmation page
  - [ ] Add user to subscription service
  - [ ] Send user confirmation email of signup
