### ISSUE TITLE
USER STORY: FAQ page

### ISSUE THREAD

**Issue by ciarantr** [ciaran-io/himawari-sushi#17]
As a **Site user** **I can** **have access to a comprehensive FAQ section** so that **I can find and answer to a question I may have**

### Todo

---
- [x] Create a reservation FAQ page.
- [x] Add common questions users may have.
- [x] Add navigation link to contact page.
